Repository bcgov/common-document-generation-service, pull requests merged in 2019-12, with the labels that each got.

#4 Add filename support to API
  app/app.js
  app/src/components/docGen.js
  app/src/components/health.js
  app/src/components/utils.js
  app/src/components/validators.js
  app/src/routes/v1.js
  app/src/routes/v1/health.js
  app/tests/unit/components/utils.spec.js
  app/tests/unit/components/validators/validators.customValidators.spec.js
  app/tests/unit/components/validators/validators.models.spec.js
Labels: bug

#9 Change build strategy to support PDF conversion via LibreOffice
  README.md
  app/docker/bindPython.sh
  app/docker/python
  app/src/components/docGen.js
  openshift/README.md
  openshift/app.bc.yaml
  openshift/app.dc.yaml
  openshift/readme.md
Labels: documentation, enhancement

#11 Link to marketing
  README.md
Labels: documentation

#12 Add custom Network Security Policies to Deployment Template
  openshift/app.dc.yaml
Labels: enhancement

#13 Restrict k8s API access to only deployers
  openshift/app.dc.yaml
Labels: enhancement

#14 Revert "Restrict k8s API access to only deployers"
  openshift/app.dc.yaml
Labels: bug
