Repository bcgov/common-document-generation-service, pull requests merged in 2020-01, with the labels that each got.

#15 Restrict k8s access to deployer service account
  openshift/app.dc.yaml
Labels: bug

#16 Add missing egress NSP to allow keycloak network traffic
  openshift/app.dc.yaml
Labels: bug

#17 Api Logging Middleware
  app/app.js
  app/package-lock.json
  app/package.json
  app/src/components/docGen.js
  app/src/middleware/apiTracker.js
  app/src/middleware/authorizedParty.js
Labels: enhancement

#19 Add Header documentation to OpenAPI YAML spec
  app/package-lock.json
  app/package.json
  app/src/docs/v1.api-spec.yaml
Labels: documentation

#24 Force libreoffice factory startup on API start
  app/app.js
  app/package-lock.json
  app/package.json
Labels: enhancement

#21 Return supported file type dictionary from CDOGS and throw 422 for unsupported conversion attempts
  app/src/assets/fileTypes.json
  app/src/components/validators.js
  app/src/docs/v1.api-spec.yaml
  app/src/routes/v1.js
  app/src/routes/v1/fileTypes.js
  app/tests/unit/components/validators/validators.customValidators.spec.js
  app/tests/unit/components/validators/validators.models.spec.js
Labels: documentation
